const insights: { en: string; es: string }[] = [
  {
    en: 'Your habits are not your actions — they are your identity made visible.',
    es: 'Tus hábitos no son tus acciones — son tu identidad hecha visible.',
  },
  {
    en: 'Small daily improvements compound into extraordinary annual results.',
    es: 'Las pequeñas mejoras diarias se acumulan en resultados extraordinarios anuales.',
  },
  {
    en: 'The quality of your attention determines the quality of your experience.',
    es: 'La calidad de tu atención determina la calidad de tu experiencia.',
  },
  {
    en: 'Self-knowledge is not a destination — it is a practice you return to every day.',
    es: 'El autoconocimiento no es un destino — es una práctica a la que regresas cada día.',
  },
  {
    en: 'The body keeps score. What signals is yours sending today?',
    es: 'El cuerpo lleva la cuenta. ¿Qué señales envía el tuyo hoy?',
  },
  {
    en: 'Your Circle of Love reflects the depth of your relationship with yourself.',
    es: 'Tu Círculo de Amor refleja la profundidad de tu relación contigo mismo.',
  },
  {
    en: 'Consistency is not perfection. It is the commitment to show up again.',
    es: 'La consistencia no es perfección. Es el compromiso de volver a aparecer.',
  },
  {
    en: 'Resistance is information. What is it telling you right now?',
    es: 'La resistencia es información. ¿Qué te está diciendo en este momento?',
  },
  {
    en: 'Your life narrative is not fixed — you are writing it with every choice.',
    es: 'Tu narrativa de vida no está fija — la escribes con cada elección.',
  },
  {
    en: 'Awareness without action is incomplete. What will you do with what you know?',
    es: 'La conciencia sin acción es incompleta. ¿Qué harás con lo que sabes?',
  },
  {
    en: 'The gap between who you are and who you want to be is closed one habit at a time.',
    es: 'La brecha entre quién eres y quién quieres ser se cierra un hábito a la vez.',
  },
  {
    en: 'Deep relationships require you to first know yourself deeply.',
    es: 'Las relaciones profundas requieren que primero te conozcas profundamente.',
  },
  {
    en: 'Energy is not found — it is generated by the habits that restore you.',
    es: 'La energía no se encuentra — se genera con los hábitos que te restauran.',
  },
  {
    en: 'A Glimpse moment is not a destination. It is an invitation to go deeper.',
    es: 'Un momento de Destello no es un destino. Es una invitación a ir más profundo.',
  },
  {
    en: 'Your external world is a mirror. What patterns do you see reflected today?',
    es: 'Tu mundo externo es un espejo. ¿Qué patrones ves reflejados hoy?',
  },
  {
    en: 'Behavior is the only language the future can hear.',
    es: 'El comportamiento es el único lenguaje que el futuro puede escuchar.',
  },
  {
    en: 'You cannot change what you refuse to see. Look clearly today.',
    es: 'No puedes cambiar lo que te niegas a ver. Mira claramente hoy.',
  },
  {
    en: 'Inner Light is not a state you achieve — it is a perspective you choose.',
    es: 'La Luz Interior no es un estado que logras — es una perspectiva que eliges.',
  },
  {
    en: 'The Readiness Score is a conversation starter, not a verdict.',
    es: 'El Puntaje de Disposición es un punto de partida, no un veredicto.',
  },
  {
    en: 'Mastery begins when curiosity outlasts frustration.',
    es: 'La Maestría comienza cuando la curiosidad supera a la frustración.',
  },
  {
    en: 'Your senses are the first channel between your inner world and reality.',
    es: 'Tus sentidos son el primer canal entre tu mundo interior y la realidad.',
  },
  {
    en: 'Rest is not the absence of progress — it is part of the process.',
    es: 'El descanso no es la ausencia de progreso — es parte del proceso.',
  },
  {
    en: 'The story you tell about yourself shapes every decision you make.',
    es: 'La historia que te cuentas sobre ti mismo moldea cada decisión que tomas.',
  },
  {
    en: 'One honest reflection today is worth more than ten perfect plans.',
    es: 'Una reflexión honesta hoy vale más que diez planes perfectos.',
  },
  {
    en: 'Illumination is not reserved for the enlightened — it is earned in the ordinary.',
    es: 'La Iluminación no está reservada para los iluminados — se gana en lo ordinario.',
  },
  {
    en: 'A habit missed once is an accident. Missed twice, it becomes a new habit.',
    es: 'Un hábito perdido una vez es un accidente. Perdido dos veces, se convierte en uno nuevo.',
  },
  {
    en: "Your biometrics are your body's honest feedback. Are you listening?",
    es: 'Tus biométricos son la retroalimentación honesta de tu cuerpo. ¿Estás escuchando?',
  },
  {
    en: 'Darkness is not failure — it is the necessary starting point of every journey.',
    es: 'La Oscuridad no es un fracaso — es el punto de partida necesario de todo camino.',
  },
  {
    en: 'Who you become through the practice matters more than the score you earn.',
    es: 'Quien te conviertes a través de la práctica importa más que la puntuación que obtienes.',
  },
  {
    en: 'Today is a new data point. What will it say about the direction you are heading?',
    es: 'Hoy es un nuevo dato. ¿Qué dirá sobre la dirección hacia la que te diriges?',
  },
];

export function insightOfTheDay(locale: 'en' | 'es' = 'en'): string {
  const dayOfYear = Math.floor(
    (Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86_400_000
  );
  const entry = insights[dayOfYear % insights.length]!;
  return entry[locale];
}
